 clone:
   - name: git
     image: woodpeckerci/plugin-git
     backend_options:
      docker:
        ekstra_hosts:
          - "gitea-sev.dk:192.168.100.10"

steps:
  - name: laravel
    image: composer:latest
    environment:
      COMPOSER_HOME: /composer
    commands:
      - apt update && apt install -y unzip git
      - cd backend
      - composer install --no-dev --optimize-autoloader
      - php artisan config:cache

  - name: frontend
    image: rust:latest
    environment:
      CARGO_HOME: /cargo
      CARGO_TARGET_DIR: /target
    commands:
      - apt update && apt install -y curl pkg-config libssl-dev
      - rustup target add wasm32-unknown-unknown
      - cargo install trunk --locked
      - cd frontend
      - trunk build --release

  - name: deploy
    image: alpine:latest
    environment:
      FTP_USER:
        from_secret: ftp_user
      FTP_PASS:
        from_secret: ftp_pass
      FTP_IP:
        from_secret: ftp_ip
    commands:
      - apk add --no-cache lftp
      - cd backend
      - lftp -e "mirror -R --only-newer public /public_html/ --exclude .env --exclude .htaccess && bye" \
          -u \"$FTP_USER\",\"$FTP_PASS\" ftp://$FTP_IP

